### PR TITLE
Metrics check

### PR DESCRIPTION
**Pull request by michalwski**
Allow to verify mongoose's metrics change after escalus story.

Example usage is [metrics_roster_SUITE here](https://github.com/esl/ejabberd_tests/blob/more-metrics-2/tests/metrics_roster_SUITE.erl#L64-L71) and [here](https://github.com/esl/ejabberd_tests/blob/more-metrics-2/tests/metrics_roster_SUITE.erl#L143-L144) and also in [clustering_commands_SUITE](https://github.com/esl/ejabberd_tests/blob/more-metrics-2/tests/cluster_commands_SUITE.erl#L97-L98)

This PR is for esl/ejabberd_tests#116

### CODE REVIEW

**Comment by lavrin** [comment]
The idea of stricter checks performed by default for each story is great, but there's a number of issues with this implementation.

The general perspective I'm taking is that, although we are not doing it in the foreseeable future due to the _best effort_ development model, we want to split Escalus into smaller libs with clearer responsibilities. Since we talked about this already, but never put down the idea _on paper_, let me sketch the lines of separation here (please don't pay much attention to the placeholder names):

- _stanzas_ - a library of XMPP stanzas (and probably predicates), possibly reusable in other XMPP related projects (server side as well as client side),
- _transports_ - a client library with support for a number of transports and features, reusable for load testing or client interfaces,
- _server interaction_ - interface to the XMPP server (now MongooseIM / ejabberd, but with potential for extensibility to other implementations).

In this light:

- `escalus_story` should not be aware of the exact server type (MongooseIM or whatever else) the tests are running against (no mention of MongooseIM in this module like `escalus_ejabberd:is_mongoose()`),
- further along this line, `escalus_story` __should not be aware of the implementation details of the server or any of the libs making up the server__ (atoms: `exometer`, `spiral`, `histogram`, etc),
- `escalus_story` should be at the XMPP level - deal with interactions between XMPP entities, not with server side details,
- metrics checks should be hidden behind `escalus_server` (ideally a behaviour, maybe someday with specializations for different server types) or in the short run at least inside `escalus_ejabberd`,
- metrics-aware story requires some server-agnostic functions (e.g. `check_metric_change`) and some server-specific functions (e.g. `get_value`) and it would make sense to put them in separate places.

**Comment by pzel** [comment]
I agree with all @lavrin said above.

**Comment by michalwski** [comment]
Valuable feedback is always much appreciated :D. Here's what I suggest:
1. `escalus_story` will have lines like:
    *  `Config = escalus_server:pre_story(ConfigIn)` instead of `CountersToCheck = counters_to_check(ConfigIn),`
    *  `escalus_server:post_story(Config)` instead of `post_story_check_counters(CountersToCheck)`
2. `escalus_server` will dispatch above function to relevant implementation based on the Config parameter.

What would you say?

**Comment by lavrin** [comment]
:+1:

**Comment by pzel** [comment]
+1

**Comment by michalwski** [comment]
How about now?

**Pull request merged**
