### PR TITLE
Add XML viewer

### PR DESCRIPTION
**Pull request by arcusfelis**
XSL XML viewer. The link is to my repo, which should be available forever (till github changes url format again at least).
It's a "standalone" version of https://chrome.google.com/webstore/detail/xv-%E2%80%94-xml-viewer/eeocglpgjdpaefaedpblffpeebgmgddk?hl=en

screenshot from 2018-01-15 18-43-41

### CODE REVIEW

**Comment by erszcz** [comment]
Nice idea! Looks really good to me, but I'd place the viewer in this repo and link appropriately.

**Comment by arcusfelis** [comment]
@erszcz It's 72 kilobytes.
And linking it to ct_reports is tricky.

**Comment by arcusfelis** [comment]
Done, it's in the repo now.

**Comment by erszcz** [comment]
:+1:

**Pull request merged**
