### PR TITLE
Update gun and rebar3_codecov

### PR DESCRIPTION
**Pull request by vkatsuba**

### CODE REVIEW

**Comment by NelsonVides** [comment]
Nice, those are very small changes 😃 
Have you tried running MIM CI with this version of escalus?

**Comment by vkatsuba** [comment]
> Nice, those are very small changes smiley
> Have you tried running MIM CI with this version of escalus?

Nop, MIM still use 1.X, but we very close to change it too.

**Comment by NelsonVides** [comment]
No no, I don't mean putting gun into mim, I mean, using this version of escalus into mim.

**Comment by vkatsuba** [comment]
> No no, I don't mean putting gun into mim, I mean, using this version of escalus into mim.

Also no, we still use old version of escalus, first of all need to make MIM works with 4.2.3 version, then try use master.

**Comment by NelsonVides** [comment]
> > No no, I don't mean putting gun into mim, I mean, using this version of escalus into mim.
> 
> Also no, we still use old version of escalus, first of all need to make MIM works with 4.2.3 version, then try use master.

I'm only concerned CI for escalus ain't that extensive, and our best test for escalus is to actually use it in MIM CI 😕

**Comment by vkatsuba** [comment]
> best test for escalus is to actually use it in MIM CI

Totally agree, then make sense to wait of updating all deps for big_tests in MIM and then we will be able to try

**Comment by vkatsuba** [comment]
The [GHA](https://github.com/esl/MongooseIM/actions/runs/1115923206) is pass, but for move this PR into release and start use it, need remove `shotgun` from MIM for `rest_client_SUITE`.

**Comment by vkatsuba** [comment]
@NelsonVides all tests was pass in PR https://github.com/esl/MongooseIM/pull/3215 with current branch. Current PR is ready for final review.

**Review by NelsonVides — APPROVED** [review]
Great!

**Pull request merged**
