### PR TITLE
Add an option to include maybe_stream_resumption step

### PR DESCRIPTION
**Pull request by kanes115**
This PR let's user tell connection module that it wants to enable stream management with `resume` option. It is now not available without specifying all the steps in `escalus_connection:start/2.` 

Now it would be enough to add `{connection_steps, default_resume}` to user spec in `escalus_connection:start/2`. This PR **does not** change the API, just extends it (with this option).

I add this as I needed it in this [PR](https://github.com/esl/MongooseIM/pull/1601)

If I miss the way I should specify that I want to use maybe_stream_resumption, let me know, please :)

### CODE REVIEW

**Comment by erszcz** [comment]
Nice idea!

However, I have a hunch it would be a bit misleading if `connection_steps` was reused in such a way, since the name suggests it's a list/group of things. Still, there's a `stream_management` (now boolean) option allowed in the user spec and handled by `maybe_stream_management` and `maybe_stream_resumption` in `escalus_session`.

Could you rework this patch to introduce a new `resume_by_default` of `stream_management` option, so that it's picked up by the relevant functions in `escalus_session`?

**Comment by erszcz** [comment]
BTW, it would be nice if there was a link in this issue to some example of the feature in use, so that it's possible to just click'n'jump to see how it looks in the code.

**Comment by erszcz** [comment]
Specifically, [`maybe_stream_management `](https://github.com/esl/escalus/blob/e7b3c87efe2204d925927f9385db37e41d61eb6d/src/escalus_session.erl#L214-L221) could have one more case clause for the new value of the option.

**Comment by arcusfelis** [comment]
Old PR, closing

**Pull request closed without merging**
